<template>
  <div class="em-page">
    <section class="em-filter">
      <el-form :model="filters" inline><el-form-item label="手册名称"><el-input v-model="filters.keyword" placeholder="请输入手册名称" clearable /></el-form-item><el-form-item label="事件类型"><el-select v-model="filters.category" placeholder="全部类型" clearable><el-option v-for="type in categories" :key="type" :label="type" :value="type" /></el-select></el-form-item><el-form-item><el-button type="primary" :icon="Search">查询</el-button><el-button :icon="Refresh" @click="resetFilters">重置</el-button></el-form-item></el-form>
    </section>

    <div class="em-actions"><el-button type="primary" :icon="Plus" @click="openEditor()">新建手册</el-button><span>共 {{ filteredManuals.length }} 条记录</span></div>
    <el-table :data="filteredManuals" border stripe style="width: 100%">
      <el-table-column type="index" label="序号" width="60" align="center" />
      <el-table-column prop="name" label="手册名称" min-width="190" />
      <el-table-column prop="category" label="事件类型" width="110" align="center"><template #default="{ row }"><el-tag size="small">{{ row.category }}</el-tag></template></el-table-column>
      <el-table-column prop="area" label="适用区域" width="150" />
      <el-table-column prop="department" label="责任部门" width="120" />
      <el-table-column label="材料数量" width="100" align="center"><template #default="{ row }">{{ row.materials.length }} 项</template></el-table-column>
      <el-table-column label="版本" width="90" align="center"><template #default="{ row }">V{{ row.version }}</template></el-table-column>
      <el-table-column prop="updatedAt" label="最近更新" width="115" />
      <el-table-column label="操作" width="180" fixed="right" align="center"><template #default="{ row }"><el-button link type="primary" size="small" @click="openPreview(row)">预览</el-button><el-button link type="primary" size="small" @click="openEditor(row)">编辑</el-button><el-button link type="danger" size="small" @click="handleDelete(row)">删除</el-button></template></el-table-column>
    </el-table>

    <el-drawer v-model="editorVisible" :title="editingId ? '编辑应急处理手册' : '新建应急处理手册'" size="820px" :close-on-click-modal="false">
      <div class="em-editor">
        <el-form ref="editorFormRef" :model="editor" :rules="rules" label-width="90px" class="em-editor__form">
          <el-row :gutter="16"><el-col :span="12"><el-form-item label="手册名称" prop="name"><el-input v-model="editor.name" placeholder="例如：火灾应急处置手册" /></el-form-item></el-col><el-col :span="12"><el-form-item label="事件类型" prop="category"><el-select v-model="editor.category" style="width:100%"><el-option v-for="type in categories" :key="type" :label="type" :value="type" /></el-select></el-form-item></el-col></el-row>
          <el-form-item label="版本" prop="version"><el-input v-model="editor.version" placeholder="例如：1.0" /></el-form-item>
          <el-row :gutter="16"><el-col :span="12"><el-form-item label="适用区域" prop="area"><el-cascader v-model="editor.area" :options="areaOptions" :props="{ checkStrictly: true }" clearable filterable style="width:100%" placeholder="请选择园区、建筑或具体区域" /></el-form-item></el-col><el-col :span="12"><el-form-item label="责任部门" prop="department"><el-select v-model="editor.department" style="width:100%"><el-option label="安全管理部" value="安全管理部" /><el-option label="工程运维部" value="工程运维部" /><el-option label="园区运营部" value="园区运营部" /></el-select></el-form-item></el-col></el-row>
          <el-form-item label="手册说明" prop="description"><el-input v-model="editor.description" type="textarea" :rows="3" placeholder="说明该手册的适用事件、使用对象及场景" /></el-form-item>
          <el-divider content-position="left">手册材料</el-divider>
          <div class="em-material-toolbar"><span>已上传 {{ editor.materials.length }} 项材料</span><el-upload action="#" :auto-upload="false" :show-file-list="false" @change="onFileChange"><el-button type="primary" plain :icon="Upload">上传材料</el-button></el-upload></div>
          <div v-if="editor.materials.length" class="em-material-list"><div v-for="(item, index) in editor.materials" :key="item.id" class="em-material-row"><div class="em-material-row__icon" :class="`is-${item.type}`"><el-icon><component :is="fileIcon(item.type)" /></el-icon></div><div class="em-material-row__body"><el-input v-model="item.name" size="small" placeholder="材料名称" /><span>{{ item.size }} · {{ item.updatedAt }}</span></div><el-select v-model="item.type" size="small" style="width:110px"><el-option v-for="type in uploadTypes" :key="type.value" :label="type.label" :value="type.value" /></el-select><el-button text type="danger" :icon="Delete" @click="editor.materials.splice(index, 1)" /></div></div>
          <el-empty v-else description="暂未上传材料" :image-size="56" />
        </el-form>
      </div>
      <template #footer><el-button @click="editorVisible = false">取消</el-button><el-button type="primary" @click="saveManual">保存</el-button></template>
    </el-drawer>

    <el-drawer v-model="previewVisible" title="手册预览" size="760px"><template v-if="preview"><div class="em-preview__heading"><div class="em-preview__badge" :style="{ background: preview.color }">{{ preview.category }}</div><h2>{{ preview.name }}</h2><p>{{ preview.description }}</p><span>版本：V{{ preview.version }} · 适用区域：{{ preview.area }} · 责任部门：{{ preview.department }}</span></div><div class="em-preview__toc"><div class="em-preview__toc-head"><b>材料目录</b><el-checkbox :model-value="isAllMaterialsSelected" :indeterminate="isMaterialsIndeterminate" @change="toggleAllMaterials">全选</el-checkbox></div><div v-for="(item,index) in preview.materials" :key="item.id" class="em-preview__item"><el-checkbox :model-value="selectedMaterialIds.includes(item.id)" @click.stop @change="toggleMaterial(item.id)" /><span>{{ String(index + 1).padStart(2, '0') }}</span><el-icon :class="`is-${item.type}`"><component :is="fileIcon(item.type)" /></el-icon><b>{{ item.name }}</b><small>{{ materialLabel(item.type) }} · {{ item.size }}</small><div class="em-preview__item-actions" @click.stop><el-button v-if="canPreview(item)" link type="primary" size="small" :icon="View" @click="openMaterialPreview(item)">预览</el-button></div></div></div></template><template #footer><el-button @click="previewVisible = false">关闭</el-button><el-button type="primary" :icon="Download" :disabled="selectedMaterialIds.length === 0" @click="downloadSelectedMaterials">打包下载（已选 {{ selectedMaterialIds.length }} 项）</el-button></template></el-drawer>
    <el-dialog v-model="materialPreviewVisible" :title="materialPreview ? `${materialPreview.name} - 预览` : '材料预览'" width="680px"><div v-if="materialPreview" class="em-material-preview"><el-icon :class="`is-${materialPreview.type}`"><component :is="fileIcon(materialPreview.type)" /></el-icon><h3>{{ materialPreview.name }}</h3><p>{{ materialLabel(materialPreview.type) }}预览</p><span>当前为原型演示，实际系统可在此处展示图片或播放视频。</span></div><template #footer><el-button @click="materialPreviewVisible = false">关闭</el-button></template></el-dialog>
    <el-dialog v-model="deleteVisible" title="删除手册" width="420px"><p class="em-delete">确定删除手册「{{ deleting?.name }}」吗？手册内的材料将一并移除。</p><template #footer><el-button @click="deleteVisible = false">取消</el-button><el-button type="danger" @click="confirmDelete">确认删除</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Delete, Document, Download, Film, MapLocation, Picture, Plus, Refresh, Search, Upload, VideoPlay, View } from '@element-plus/icons-vue'
import type { FormInstance, FormRules } from 'element-plus'
type MaterialType = 'document' | 'route' | 'image' | 'video'
interface Material { id: number; name: string; type: MaterialType; size: string; updatedAt: string }
interface Manual { id: number; name: string; category: string; area: string; department: string; description: string; version: string; updatedAt: string; color: string; materials: Material[] }
const categories = ['火灾事故', '自然灾害', '设备事故', '治安事件', '公共卫生']; const areas = ['全园区', 'CT楼', 'FF楼', '海关联检大楼(OB)', '地下车库']
const manuals = ref<Manual[]>([
  { id: 1, name: '火灾应急处置手册', category: '火灾事故', area: '全园区', department: '安全管理部', description: '覆盖火情报警、初期扑救、人员疏散、应急联动及事后报告的全流程处置指引。', version: '3.0', updatedAt: '2026-07-16', color: '#e65a54', materials: [{ id: 11, name: '火灾应急处置流程', type: 'document', size: '2.4 MB', updatedAt: '2026-07-16' }, { id: 12, name: 'CT楼逃生路线图', type: 'route', size: '1.8 MB', updatedAt: '2026-07-12' }, { id: 13, name: '灭火器使用演示视频', type: 'video', size: '28.6 MB', updatedAt: '2026-07-10' }] },
  { id: 2, name: '台风暴雨防汛应急手册', category: '自然灾害', area: '全园区', department: '园区运营部', description: '用于台风、暴雨天气下的预警响应、物资检查、排涝抢险和人员避险组织。', version: '2.1', updatedAt: '2026-07-11', color: '#3e91d3', materials: [{ id: 21, name: '防汛应急响应指引', type: 'document', size: '1.6 MB', updatedAt: '2026-07-11' }, { id: 22, name: '地下车库防汛示意图', type: 'image', size: '3.2 MB', updatedAt: '2026-07-09' }, { id: 23, name: '防汛物资清单', type: 'document', size: '680 KB', updatedAt: '2026-07-08' }] },
  { id: 3, name: '配电系统故障应急手册', category: '设备事故', area: 'CT楼', department: '工程运维部', description: '针对突发断电、配电设备异常和重要负荷供电中断制定的排查与恢复手册。', version: '1.0', updatedAt: '2026-07-08', color: '#d99a2b', materials: [{ id: 31, name: '配电故障分级处置指引', type: 'document', size: '1.2 MB', updatedAt: '2026-07-08' }, { id: 32, name: 'CT楼配电系统图', type: 'image', size: '4.5 MB', updatedAt: '2026-07-05' }] },
  { id: 4, name: '治安突发事件处置手册', category: '治安事件', area: '海关联检大楼(OB)', department: '安全管理部', description: '面向可疑人员、聚集冲突和暴力风险事件的发现、控制、上报与协同处置。', version: '1.2', updatedAt: '2026-06-20', color: '#8667c8', materials: [{ id: 41, name: '治安事件现场处置卡', type: 'document', size: '920 KB', updatedAt: '2026-06-20' }, { id: 42, name: '安保联络与集结路线图', type: 'route', size: '1.1 MB', updatedAt: '2026-06-18' }] },
])
const filters = reactive({ keyword: '', category: '' }); const editorVisible = ref(false); const previewVisible = ref(false); const materialPreviewVisible = ref(false); const deleteVisible = ref(false); const editingId = ref<number | null>(null); const preview = ref<Manual | null>(null); const materialPreview = ref<Material | null>(null); const selectedMaterialIds = ref<number[]>([]); const deleting = ref<Manual | null>(null); const editorFormRef = ref<FormInstance>(); let materialSeed = 100
const areaOptions = [{
  value: '全园区',
  label: '全园区',
  children: [
    { value: 'CT楼', label: 'CT楼', children: [{ value: '1F', label: '1F', children: [{ value: '办公区', label: '办公区' }, { value: '配电房', label: '配电房' }] }, { value: '2F', label: '2F' }, { value: '屋顶层', label: '屋顶层' }] },
    { value: 'FF楼', label: 'FF楼', children: [{ value: '1F', label: '1F', children: [{ value: '作业区', label: '作业区' }, { value: '卸货平台', label: '卸货平台' }] }, { value: 'S夹层', label: 'S夹层' }, { value: '7F', label: '7F' }, { value: '8F', label: '8F' }] },
    { value: '海关联检大楼(OB)', label: '海关联检大楼(OB)', children: [{ value: '1F', label: '1F' }, { value: '2F', label: '2F' }] },
    { value: '地下车库', label: '地下车库', children: [{ value: 'B1', label: 'B1' }, { value: 'B2', label: 'B2' }] },
  ],
}]
const editor = reactive({ name: '', category: '', area: [] as string[], department: '安全管理部', description: '', version: '', materials: [] as Material[] })
const uploadTypes = [{ value: 'document' as MaterialType, label: '处置文件', icon: Document, color: '#3e91d3' }, { value: 'route' as MaterialType, label: '逃生路线', icon: MapLocation, color: '#e65a54' }, { value: 'image' as MaterialType, label: '现场图纸', icon: Picture, color: '#d99a2b' }, { value: 'video' as MaterialType, label: '应急视频', icon: VideoPlay, color: '#8667c8' }]
const rules: FormRules = { name: [{ required: true, message: '请输入手册名称', trigger: 'blur' }], category: [{ required: true, message: '请选择事件类型', trigger: 'change' }], area: [{ required: true, message: '请选择适用区域', trigger: 'change' }], department: [{ required: true, message: '请选择责任部门', trigger: 'change' }], description: [{ required: true, message: '请输入手册说明', trigger: 'blur' }], version: [{ required: true, message: '请输入版本号', trigger: 'blur' }] }
const filteredManuals = computed(() => manuals.value.filter(item => (!filters.keyword || item.name.includes(filters.keyword)) && (!filters.category || item.category === filters.category)))
function resetFilters() { filters.keyword = ''; filters.category = '' }; function materialLabel(type: MaterialType) { return ({ document: '处置文件', route: '逃生路线', image: '现场图纸', video: '应急视频' })[type] }; function fileIcon(type: MaterialType) { return ({ document: Document, route: MapLocation, image: Picture, video: Film })[type] }
function materialTypes(manual: Manual) { return uploadTypes.map(type => ({ ...type, count: manual.materials.filter(item => item.type === type.value).length })).filter(item => item.count) }
function toAreaPath(area: string): string[] { return area === '全园区' ? ['全园区'] : ['全园区', area] }
function openEditor(manual?: Manual) { editingId.value = manual?.id ?? null; Object.assign(editor, manual ? { name: manual.name, category: manual.category, area: toAreaPath(manual.area), department: manual.department, description: manual.description, version: manual.version, materials: manual.materials.map(item => ({ ...item })) } : { name: '', category: '火灾事故', area: ['全园区'], department: '安全管理部', description: '', version: '1.0', materials: [] }); editorVisible.value = true }
function onFileChange(file: any) { const name = file.name.replace(/\.[^.]+$/, ''); editor.materials.push({ id: ++materialSeed, name, type: 'document', size: file.size ? `${Math.max(1, Math.round(file.size / 1024))} KB` : '待上传', updatedAt: '2026-07-17' }) }
function saveManual() { const today = '2026-07-17'; const area = editor.area.join(' / '); if (editingId.value) { const index = manuals.value.findIndex(item => item.id === editingId.value); manuals.value[index] = { ...manuals.value[index], ...editor, area, materials: editor.materials.map(item => ({ ...item })), updatedAt: today } } else { const id = Math.max(...manuals.value.map(item => item.id)) + 1; manuals.value.unshift({ id, ...editor, area, materials: editor.materials.map(item => ({ ...item })), updatedAt: today, color: '#3e91d3' }) } editorVisible.value = false }
function canPreview(material: Material) { return material.type === 'image' || material.type === 'video' }
function openMaterialPreview(material: Material) { materialPreview.value = material; materialPreviewVisible.value = true }
const isAllMaterialsSelected = computed(() => Boolean(preview.value?.materials.length) && selectedMaterialIds.value.length === preview.value!.materials.length)
const isMaterialsIndeterminate = computed(() => selectedMaterialIds.value.length > 0 && !isAllMaterialsSelected.value)
function toggleMaterial(id: number) { selectedMaterialIds.value = selectedMaterialIds.value.includes(id) ? selectedMaterialIds.value.filter(item => item !== id) : [...selectedMaterialIds.value, id] }
function toggleAllMaterials(checked: boolean) { selectedMaterialIds.value = checked && preview.value ? preview.value.materials.map(item => item.id) : [] }
function downloadSelectedMaterials() { if (!preview.value || selectedMaterialIds.value.length === 0) return; const selected = preview.value.materials.filter(item => selectedMaterialIds.value.includes(item.id)); const content = selected.map(item => `${item.name}\t${materialLabel(item.type)}\t${item.size}`).join('\n'); const blob = new Blob([`手册材料打包清单\n${content}`], { type: 'text/plain;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${preview.value.name}_材料包.txt`; link.click(); URL.revokeObjectURL(link.href) }
function openPreview(manual: Manual) { preview.value = manual; selectedMaterialIds.value = []; previewVisible.value = true }; function handleDelete(manual: Manual) { deleting.value = manual; deleteVisible.value = true }; function confirmDelete() { if (deleting.value) manuals.value = manuals.value.filter(item => item.id !== deleting.value!.id); deleteVisible.value = false; deleting.value = null }
</script>

<style scoped>
.em-page { min-width:1080px; max-width:1500px; padding:24px; color:#27334a; }.em-filter { padding:16px 16px 0; margin-bottom:16px; background:#fafbfc; border-radius:4px; }.em-filter :deep(.el-input),.em-filter :deep(.el-select) { width:165px; }.em-actions { display:flex; align-items:center; gap:16px; margin-bottom:16px; }.em-actions span { font-size:13px; color:#909399; }
.em-editor { padding:0 8px; }.em-editor__form :deep(.el-alert) { margin-bottom:20px; }.em-material-toolbar { display:flex; justify-content:space-between; align-items:center; padding:10px 0 14px; border-bottom:1px solid #edf0f5; }.em-material-toolbar span { color:#8490a2; font-size:12px; }.em-material-list { margin:12px 0 18px; border:1px solid #e7ecf3; border-radius:5px; }.em-material-row { display:flex; align-items:center; gap:10px; padding:11px 12px; border-bottom:1px solid #eef1f5; }.em-material-row:last-child { border-bottom:0; }.em-material-row__icon { display:grid; place-items:center; width:32px; height:32px; background:#edf5ff; color:#3e91d3; border-radius:4px; }.em-material-row__body { flex:1; min-width:0; }.em-material-row__body span { display:block; margin-top:4px; font-size:12px; color:#8a95a6; }.is-route { color:#e65a54!important; }.is-image { color:#d99a2b!important; }.is-video { color:#8667c8!important; }.em-preview__heading { padding:18px; background:#f6f9fd; border-left:3px solid #3e91d3; }.em-preview__badge { display:inline-block; padding:3px 8px; color:#fff; font-size:12px; border-radius:3px; }.em-preview__heading h2 { margin:8px 0 5px; font-size:19px; }.em-preview__heading p { color:#6d7890; line-height:1.5; font-size:13px; }.em-preview__heading span { display:block; margin-top:8px; color:#8a95a5; font-size:12px; }.em-preview__toc { margin-top:22px; }.em-preview__toc-head { display:flex; justify-content:space-between; align-items:center; padding:0 8px 8px; }.em-preview__item { display:flex; align-items:center; gap:10px; padding:12px 8px; border-bottom:1px solid #eef1f5; }.em-preview__item:hover { background:#f7faff; }.em-preview__item > span { color:#a1abba; font-size:12px; }.em-preview__item b { min-width:0; flex:1; font-size:13px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.em-preview__item small { color:#909399; font-size:12px; white-space:nowrap; }.em-preview__item-actions { display:flex; gap:8px; flex-shrink:0; }.em-material-preview { display:flex; flex-direction:column; align-items:center; justify-content:center; min-height:260px; color:#8390a3; background:#fafbfd; border:1px dashed #dce3ed; }.em-material-preview > .el-icon { font-size:46px; }.em-material-preview h3 { margin:12px 0 5px; color:#445069; font-size:16px; }.em-material-preview p,.em-material-preview span { font-size:13px; }.em-material-preview span { margin-top:5px; }.em-delete { color:#5e6a7e; line-height:1.6; }
</style>
